#!/bin/sh

# This script modifies the dwm status bar using the xsetroot command. It should
# be run from ~/.xinitrc or ~/.xsession as a background process.

delim() {
	echo "|"
}

status() {
	# ./dwmcpu
	# delim
	# ./dwmdisk
	# delim
	# ./dwmnetwork
	# delim
	dwmclock
}

while :; do
 	xsetroot -name "$(status | tr '\n' ' ')"
	sleep 0.5
done
