#!/bin/sh

if [ ! -e /sys/class/power_supply/BAT0 ]
then
	exit 1
fi

if [ "$(cat /sys/class/power_supply/BAT0/status)" = "Charging" ]
then
	# icon="[~~]-"
	icon="⚡"
else
	# icon="[==]-"
	icon="🔋"
fi

printf "%s %d%%" $icon $(cat /sys/class/power_supply/BAT0/capacity)
